version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7055:8080"  
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ApibackendDb;User=sa;Password=ApiFirstJob;
    networks:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_db
    environment:
      SA_PASSWORD: "ApiFirstJob"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - backend

networks:
  backend:
    driver: bridge
